typography_spectrum: 0.37352
color:
  brandColors:
    - '#131313'
    - '#FAFAFA'
    - '#4E4247'
    - '#B64067'
    - '#DC8798'
  brandStrength: 0.5
  lightness: 0.9486216
  saturation: 0.375
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2900506
analytics:
  google: null
  facebook: null
  twitter: null
name: Kenn Moffitt
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Tools and apps
    id: 1764e0b6-9d9e-4f8b-8ce3-e9fbc6ce82b0
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Pixels to the People
description: All things digital with a healthy dose of science and common sense.
purpose: []
