name: Kenn Moffitt
favicon: null
layout_spectrum: 0.76357
typography_spectrum: 0.37352
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Pixels to the People
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f07818'
    - '#f0a830'
    - '#fcebb6'
    - '#78c0a8'
    - '#5e412f'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
