title: Pixels to the People
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.375
  brandStrength: 0.25
  lightness: 0.9486216
  brandColors:
    - '#131313'
    - '#FAFAFA'
    - '#4E4247'
    - '#B64067'
    - '#DC8798'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Kenn Moffitt
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.37352
layout_spectrum: 0.455312
